//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfCulture.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdType { get; set; }
        public int IdGroup { get; set; }
    
        public virtual TypeRequest TypeRequest { get; set; }
        public virtual User User { get; set; }
        public virtual Group Group { get; set; }
    }
}
