//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace HouseOfCulture.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Groups = new HashSet<Group>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Patronymic { get; set; }

        public string Shortname => $"{Surname} {Firstname[0]}. {Patronymic[0]}.";
        public string Fullname => $"{Surname} {Firstname} {Patronymic}";
        public Nullable<System.DateTime> DateBirth { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> IdUser { get; set; }

        public string GroupsString => string.Join(", ", Groups.Select(x => x.Name));
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
    }
}
